					
<? if($this->message) {
	switch ($this->message) {
		case 'apiError':
			echo "\t\t\t<p class=\"error\">There was an error while talking to Facebook API. Try again please.</p>\n";
			break;
		case 'csrfError':
			echo "\t\t\t<p class=\"error\">There was a security issue. Try again from <a href='/register'>this link</a> please.</p>\n";
			break;
		case 'noPages':
			echo "\t\t\t<p class=\"error\">Your Facebook account doesn't administer any pages!<br /><a href='".$this->logoutUrl."'>Logout</a> and use another account.</p>\n";
			break;
		case 'alreadyExists':
			echo "\t\t\t<p class=\"error\">Some pages are already in the database.</p>\n";
		case 'success':
			echo '
			<p class="infoBox">Page has been added to the database. Now you have to invite our GoodData user <strong>facebook-gooddata@keboola.com</strong> to your project and grant it admin role. See the screenshot:<br /> <a href="/img/gd-addUser.png" class="preview"><img src="/img/gd-addUser-thumb.png" /></a></p>
';
			break;
	}
}?>

<? if($this->form) {?>
			<div class="infoBox">
				<ol>
					<li>Enter your email and pick pages you administer which you want to watch.<ul>
						<li>If you already have some page in our database you can't pick it again.</li>
					</ul></li>
					<li>Next you should create a project in GoodData and get it's id (optional). This you will find also in url, see the screenshot:<br /> <a href="/img/gd-pid.png" class="preview"><img src="/img/gd-pid-thumb.png" /></a></li>
				</ol>
			</div>
			<div class="form">
<?=$this->form?>
			</div>
<? }?>