					
<? if($this->message) {
	switch ($this->message) {
		case 'apiError':
			echo "\t\t\t<p class=\"error\">There was an error while talking to Facebook API. Try again please.</p>\n";
			break;
		case 'csrfError':
			echo "\t\t\t<p class=\"error\">There was a security issue. Try again from <a href='/register'>this link</a> please.</p>\n";
			break;
		case 'alreadyExists':
			echo "\t\t\t<p class=\"error\">This page is already in the database!</p>\n";
			break;
		case 'success':
			echo '
			<p class="infoBox">Page has been added to the database. Now you have to invite our GoodData user <strong>facebook-gooddata@keboola.com</strong> to your project and grant it admin role. See the screenshot:<br /> <a href="/img/gd-addUser.png" class="preview"><img src="/img/gd-addUser-thumb.png" /></a></p>
';
			break;
	}
}?>

<? if($this->form) {?>
			<div class="infoBox">
				<ol>
					<li>Enter page name and id. You can get page's id from url when you try to edit your page, see the screenshot:<br /> <a href="/img/fb-pageId.png" class="preview"><img src="/img/fb-pageId-thumb.png" /></a></li>
					<li>Next you have to create a project in GoodData and get it's id. This you will find also in url, see the screenshot:<br /> <a href="/img/gd-pid.png" class="preview"><img src="/img/gd-pid-thumb.png" /></a></li>
				</ol>
			</div>
			<div class="form" style="width:400px">
<?=$this->form?>
			</div>
<? }?>