<div class="rightSidebar">
	<div class="sidebar">
		<div class="box lastBox">
			<!-- Pravý sloupec -->

			<a href="/google-analytics/logout">Logout from Google</a>

		</div>
	</div>
	<div class="content">
		<div class="firstBox">
			<?=$this->flashMessages()?>

			<h2><?=$this->translate('google.analytics.register.info')?></h2>

			<?
			if (isset($this->form)) {
				echo $this->form;
			}
			?>
		</div>
	</div>
</div>