<?
$this->jQuery()->addJavascriptFile('/js/jquery.validate/jquery.validate.min.js')->addOnLoad('
	$("form").validate({
		errorContainer: ".loginErrors",
		errorLabelContainer: ".loginErrors .wrap2",
		rules: {
			email: {
				required: true,
				email: true
			},
			password: {
				required: true
			}

		},
		messages: {
			email: {
				required: "'.$this->translate('jquery.validation.email.required').'",
				email: "'.$this->translate('jquery.validation.email').'"
			},
			password: {
				required: "'.$this->translate('jquery.validation.password.required').'"
			}

		}
	});
');
?>
<div class="loginForm">
	<?=$this->form->setAction($this->url());?>
	<p class="links">
		<a href="/auth/register"><?=$this->translate('auth.index.signUp')?></a> |
		<a href="/auth/lost-password"><?=$this->translate('auth.index.lostPassword')?></a>
	</p>
</div>