<?
$this->jQuery()->addJavascriptFile('/js/livequery.js')->addJavascript('
	$(".formCaptcha strong, .formElement strong").livequery(function(){
		$(this).corner("5px");
	});
');
$this->jQuery()->addOnLoad('
	setTimeout("$(\".zendError\").remove();", 5000);
	$(".inputText, .inputPassword, .inputCaptcha").corner("5px");
	$(".formCaptcha img").corner("10px");
	$(".formCaptcha img").click(function() {
		$.ajax({
			url: "/auth/refresh-captcha",
			dataType: "json",
			success: function(data) {
				$(".formCaptcha img").attr("src", data.src);
				$("#captcha-id").attr("value", data.id);
			}
		});
	});
');
?>
<div class="registerForm">
	<?=$this->form;?>
</div>