<div class="screenshots screenshots2">
	<div class="screenshot">
		<img src="/img/screenshots/date+freedom.png" alt="" />
		<p>Freely select the time period you want to see</p>
	</div>
	<div class="screenshot">
		<img src="/img/screenshots/performance+report.png" alt="" />
		<p>Performance reports</p>
	</div>
	<div class="screenshot">
		<img src="/img/screenshots/deliver+on+right+place.png" alt="" />
		<p>Information where you need it - and together!</p>
	</div>
	<div class="screenshot">
		<img src="/img/screenshots/where+you+grow.png" alt="" />
		<p>See developments by regions</p>
	</div>
	<div class="screenshot">
		<img src="/img/screenshots/own+metric.png" alt="" />
		<p>Define yourself, what is most important for you (we will help!)</p>
	</div>
	<div class="screenshot">
		<img src="/img/screenshots/daily+data.png" alt="" />
		<p>No rounding - you get the granularity you need to make the right decisions.</p>
	</div>
</div>