<div class="content">
	<h1>Keboola Analytics' Facebook App</h1>
	<p>The Keboola Analytics' Facebook App keeps track of your fan base over time, monitors your page reach and follows your stories to closely watch your brand's impact on the social network.</p>
	<p>We keep and maintain your data indefinitely (no 35-day FB limit), and keep the granularity down to a single day (no FB's weekly totalling). You can also combine data from multiple pages to truly rule your Facebook empire.</p>
	<p>Thanks to the GoodData platform powering our app, you can create your own reports, insert your KPIs, play with your data and drill into them any way you like.</p>
	<p>By keeping your finger on the pulse of your Facebook pages, you can focus your marketing dollars where they do the most good for your brand. Speaking of dollars, here are the plans and prices in case you were wondering:</p>
	<table>
		<tr>
			<td>$19 per month</td>
			<td>1 Facebook Page</td>
			<td>1 User</td>
		</tr>
		<tr>
			<td>$99 per month</td>
			<td>6 Facebook Pages</td>
			<td>4 Users</td>
		</tr>
		<tr>
			<td>$299 per month</td>
			<td>20 Facebook Pages</td>
			<td>10 Users</td>
		</tr>
		<tr>
			<td>$499 per month</td>
			<td>40 Facebook Pages</td>
			<td>20 Users</td>
		</tr>
	</table>
	<p>And yes, we can take this data and mash it with your own. How many of your Facebook fans become customers? How does your Facebook ad spending affect your fan base? Did an event bring the effect your agency promised? All these answers (and more) are right in there.</p>
	<p>Want to see your own data in a dashboard like the one below? <a href="/auth/register">Sign up, log in and get started</a> - and of course, contact us (<a href="mailto:sales@keboola.com">sales@keboola.com</a>) if we can be of any help!</p>
	<div class="screenshots screenshots2">
		<img src="/img/screenshots/t3.png" alt="" />
		<img src="/img/screenshots/t5.png" class="last" alt="" />
	</div>
</div>