<?
$usedAccountsCount = count($this->userAccounts);
$remainingAccountsCount = $this->paidAccountsCount - $usedAccountsCount;

$this->jQuery()->addOnLoad('
	$("#submit").attr("disabled", "disabled");
	$("#paypalButton").attr("disabled", "disabled");
	$("#selectPlan").change(function(){
		setToken(idUser, $("#selectPlan option:selected").attr("rel"));
	});
');

if($this->userToConnector) {
	$this->jQuery()->addOnLoad('
	$("input[type=\'checkbox\']").change(function(){
		var checkedCount = $("input[type=\'checkbox\']:checked").not(":disabled").length;
		var remainingCount = totalRemainingAccountsCount-checkedCount;
		$("#remainingAccountsCount").text(remainingCount);
		if (remainingCount >= 0 && $("input[type=\'checkbox\']:checked").not(":disabled").size() > 0) {
			$("#submit").removeAttr("disabled").attr("src", "/img/button-save.png");
		} else {
			$("#submit").attr("disabled", "disabled").attr("src", "/img/button-save-inactive.png");
		}
	});
	');
}

$this->jQuery()->addJavascript('
	var remainingAccountsCount = '.$remainingAccountsCount.';
	var totalRemainingAccountsCount = '.$remainingAccountsCount.';
	var idUser = '.$this->user->id.';

	function setToken(idUser, plan, tries)
	{
		if(tries===undefined) {
			tries = 3;
		}

		if (!tries) {
			alert("'.$this->translate('facebook.register.getTokenError').'");
		} else {
			$.get("/facebook/generate-token/plan/"+plan, function(data) {
  				if(data.status=="ok") {
  					$("#customField").val(idUser+"-"+plan+"-"+data.token);
  					$("#paypalButton").removeAttr("disabled").attr("src", "/img/button-subscribe.png");
				} else {
					getToken(idUser, plan, tries-1);
				}
			});
		}
	}
');
?>

<div class="rightSidebar">
	<div class="sidebar">
		<div class="box">
			<h2><?=$this->translate('facebook.register.subscribedPlan')?></h2>
			<? if($this->userToConnector) {?>
			<table class="subscribedPlan">
				<tr>
					<th><?=$this->translate('facebook.register.pagesCount')?></th>
					<td class="pagesCount"><?=$usedAccountsCount?> / <?=$this->paidAccountsCount?></td>
				</tr>
				<tr>
					<th><?=$this->translate('facebook.register.usersCount')?></th>
					<td class="usersCount">1 / <?=$this->subscribedPlan->usersCount?></td>
				</tr>
				<tr>
					<th><?=$this->translate('facebook.register.price')?></th>
					<td class="price">$<?=$this->subscribedPlan->price?></td>
				</tr>
			</table>
			<?} else {?>
				<?=$this->translate('facebook.register.noSubscribedPlan')?>
			<?}?>
		</div>

		<div class="box lastBox">
			<h2><?=$this->translate('facebook.register.changePlan')?></h2>
			<form action="<?=$this->config->paypal->url?>" method="post" class="paypal">
				<div>
					<input type="hidden" name="business" value="<?=$this->config->paypal->merchantId?>" />
					<input type="hidden" name="cmd" value="_xclick-subscriptions" />
					<input type="hidden" name="item_name" value="<?=$this->config->app->name?>" />
					<input type="hidden" name="currency_code" value="USD" />
<?if(!$this->subscribedPlan) {?>
					<input type="hidden" name="a1" value="1" />
					<input type="hidden" name="p1" value="7" />
					<input type="hidden" name="t1" value="D" />
<?}?>
					<select name="a3" id="selectPlan" class="selectPlan">
						<option selected="selected" disabled="disabled">- <?=$this->translate('facebook.register.choosePlan')?> -</option>
						<?foreach($this->pricePlans as $p) {
						$args = '';
						if ($this->subscribedPlan && $p->accountsCount <= $this->subscribedPlan->accountsCount) {
							// disable lower price plans than subscribed
							$args = ' disabled="disabled"';
						}
						echo '<option'.$args.' value="'.$p->price.'" rel="'.$p->id.'">'
							. $this->translate('facebook.register.planOption', $p->accountsCount, $p->usersCount, $p->price)
							. '</option>';
					}?>
					</select>
				</div>
				<div>
					<input type="hidden" name="p3" value="1" />
					<input type="hidden" name="t3" value="M" />
					<input type="hidden" name="src" value="1" />
					<input type="hidden" name="return" value="<?=$this->baseUrl?>/facebook/subscribe" />
					<input type="hidden" name="cancel_return" value="<?=$this->baseUrl?>/facebook/register" />
					<input type="hidden" name="custom" id="customField" value="" />
					<input type="image" id="paypalButton" src="/img/button-subscribe-inactive.png" name="submit" alt="PayPal - The safer, easier way to pay online!" />
					<img alt="" src="https://www.paypal.com/en_US/i/scr/pixel.gif" />
				</div>
			</form>
			<?if($this->subscribedPlan){?>
			<div class="right"><a href="<?=$this->config->paypal->url?>?cmd=_subscr-find&alias=<?=$this->config->paypal->merchantId?>"><?=$this->translate('facebook.register.unsubscribe')?></a></div>
			<?}?>
		</div>
	</div>
	<div class="content">
		<h2><?=$this->translate('facebook.register.info')?></h2>
		<?if(!$this->userToConnector) {?>
			<p class="warning notice"><span class="wrap"><?=$this->translate('facebook.register.subscribeFirst')?></span></p>
		<?}?>
		<?if ($this->messages) {?>
		<div class="flashMessages"><div class="wrap">
			<?foreach($this->messages as $m) {?>
				<p class="warning notice"><span class="wrap"><?=$this->translate($m)?></span></p>
			<?}?>
		</div></div>
		<?}?>
		<p><?=$this->translate('facebook.register.remaining')?>: <strong id="remainingAccountsCount"><?=$remainingAccountsCount?></strong></p>
		<?=$this->form?>
	</div>
</div>