<?
$usedAccountsCount = count($this->userAccounts);
$remainingAccountsCount = $this->paidAccountsCount - $usedAccountsCount;

$usedInvitationsCount = count($this->usedInvitations)+1;
$remainingInvitationsCount = $this->paidUsersCount-$usedInvitationsCount;

$this->jQuery()
	->addJavascriptFile('/js/jquery.confirm-1.3.js')
	->addOnLoad('
	$(".confirm").confirm({
		timeout: 3000,
		dialogShow: "fadeIn",
		dialogSpeed: "slow",
		buttons: {
			wrapper: "<button></button>",
			separator: " "
		}
	});
	$(".inputText, textarea").corner("5px");
	$("#submit").attr("disabled", "disabled");
	$("#paypalButton").attr("disabled", "disabled");
	$("#selectPlan").change(function(){
		setToken(idUser, $("#selectPlan option:selected").attr("rel"));
	});
	$("input[type=\'checkbox\']").change(function(){
		var checkedCount = $("input[type=\'checkbox\']:checked").not(":disabled").length;
		var remainingCount = totalRemainingAccountsCount-checkedCount;
		$("#remainingAccountsCount").text(remainingCount);
		if (remainingCount >= 0 && $("input[type=\'checkbox\']:checked").not(":disabled").size() > 0) {
			$("#submit").removeAttr("disabled").attr("src", "/img/button-save.png");
		} else {
			$("#submit").attr("disabled", "disabled").attr("src", "/img/button-save-inactive.png");
		}
	});
	$("#showInviteForm").click(function(){
		$(".inviteForm").show("slow", function(){
			$("#hideInviteForm").show();
			$("#showInviteForm").hide();
		});
		return false;
	});
	$("#hideInviteForm").click(function(){
		$(".inviteForm").hide("slow", function(){
			$("#showInviteForm").show();
			$("#hideInviteForm").hide();
		});
		return false;
	});
');

if ($remainingInvitationsCount > 0) {
	$this->jQuery()->addOnLoad('
	$("#invite").removeAttr("disabled").attr("src", "/img/button-invite.png");
	');
}

$this->jQuery()->addJavascript('
	var remainingAccountsCount = '.$remainingAccountsCount.';
	var totalRemainingAccountsCount = '.$remainingAccountsCount.';
	var idUser = '.$this->user->id.';

	function setToken(idUser, plan, tries)
	{
		if(tries===undefined) {
			tries = 3;
		}

		if (!tries) {
			alert("'.$this->translate('facebook.register.getTokenError').'");
		} else {
			$.get("/facebook/generate-token/plan/"+plan, function(data) {
  				if(data.status=="ok") {
  					$("#customField").val(data.token);
  					$("#paypalButton").removeAttr("disabled").attr("src", "/img/button-subscribe.png");
				} else {
					getToken(idUser, plan, tries-1);
				}
			});
		}
	}
');
?>

<div class="rightSidebar">
<? if($this->userToConnector) {?>
	<div class="sidebar">
		<div class="box">
			<h2><?=$this->translate('facebook.register.subscribedPlan')?></h2>
			<table class="subscribedPlan">
				<tr>
					<th><?=$this->translate('facebook.register.pagesCount')?></th>
					<td class="pagesCount"><?=$usedAccountsCount?> / <?=$this->paidAccountsCount?></td>
				</tr>
				<tr>
					<th><?=$this->translate('facebook.register.usersCount')?></th>
					<td class="usersCount"><?=$usedInvitationsCount?> / <?=$this->paidUsersCount?></td>
				</tr>
				<tr>
					<th><?=$this->translate('facebook.register.price')?></th>
					<td class="price">$<?=$this->subscribedPlan->price?></td>
				</tr>
			</table>
		</div>

		<div class="box lastBox">
			<h2><?=$this->translate('facebook.register.changePlan')?></h2>
			<form action="<?=$this->config->paypal->url?>" method="post" class="paypal">
				<div>
					<input type="hidden" name="business" value="<?=$this->config->paypal->merchantId?>" />
					<input type="hidden" name="cmd" value="_xclick-subscriptions" />
					<input type="hidden" name="item_name" value="<?=$this->config->app->name?>" />
					<input type="hidden" name="currency_code" value="USD" />
					<select name="a3" id="selectPlan" class="selectPlan">
						<option selected="selected" disabled="disabled">- <?=$this->translate('facebook.register.choosePlan')?> -</option>
						<?foreach($this->pricingPlans as $p) {
						$args = '';
						if ($this->subscribedPlan && $p->accountsCount <= $this->subscribedPlan->accountsCount) {
							// disable lower price plans than subscribed
							$args = ' disabled="disabled"';
						}
						echo '<option'.$args.' value="'.$p->price.'" rel="'.$p->id.'">'
							. $this->translate('facebook.register.planOption', $p->accountsCount, $p->usersCount, $p->price)
							. '</option>';
					}?>
					</select>
				</div>
				<div>
					<input type="hidden" name="p3" value="1" />
					<input type="hidden" name="t3" value="M" />
					<input type="hidden" name="src" value="1" />
					<input type="hidden" name="return" value="<?=$this->baseUrl?>/facebook/subscribe" />
					<input type="hidden" name="cancel_return" value="<?=$this->baseUrl?>/facebook/register" />
					<input type="hidden" name="custom" id="customField" value="" />
					<input type="image" id="paypalButton" src="/img/button-subscribe-inactive.png" name="submit" alt="PayPal - The safer, easier way to pay online!" />
					<img alt="" src="https://www.paypal.com/en_US/i/scr/pixel.gif" />
				</div>
			</form>
			<?if($this->subscribedPlan){?>
			<div class="right"><a href="<?=$this->config->paypal->url?>?cmd=_subscr-find&alias=<?=$this->config->paypal->merchantId?>"><?=$this->translate('facebook.register.unsubscribe')?></a></div>
			<?}?>
		</div>
	</div>
<? }?>
	<div class="content">
		<div class="firstBox">
			<?if(!$this->userToConnector) {?>
			<p class="warning notice"><span class="wrap"><?=$this->translate('facebook.register.subscribeFirst', '/facebook/choose-plan')?></span></p>
			<?}?>
			<?=$this->flashMessages()?>

			<h2><?=$this->translate('facebook.register.info')?></h2>
			<p><?=$this->translate('facebook.register.remaining')?>: <strong id="remainingAccountsCount"><?=$remainingAccountsCount?></strong></p>
			<?=$this->facebookSetupForm?>
		</div>
<? if($this->userToConnector) {?>
		<div class="box">
			<h2><?=$this->translate('facebook.register.inviteInfo')?></h2>
			<p><?=$this->translate('facebook.register.inviteRemaining')?>: <strong id="remainingInvitationsCount"><?=$remainingInvitationsCount?></strong></p>
			<?if($remainingInvitationsCount > 0) {?>
			<p>
				<a href="#" id="showInviteForm"><?=$this->translate('facebook.register.showInvitationForm')?></a>
				<a href="#" id="hideInviteForm"><?=$this->translate('facebook.register.hideInvitationForm')?></a>
			</p>
			<?}?>
			<div class="inviteForm">
				<?=$this->inviteForm?>
				<div class="clear">&nbsp;</div>
			</div>
			<?if($usedInvitationsCount > 1) {?>
				<h2><?=$this->translate('facebook.register.invitedUsers')?></h2>
				<ul class="invitedUsers">
					<?foreach($this->usedInvitations as $u) {?>
					<li><?=$u->email?> <!--a href="/facebook/disable/id/<?=$u->id?>" class="confirm"><?=$this->translate('facebook.register.disable')?></a--></li>
					<?}?>
				</ul>
			<?}?>
		</div>
<? }?>
	</div>
</div>