<?
$this->headLink()
	->appendStylesheet('/css/52framework/reset.css')
	->appendStylesheet('/css/52framework/css3.css')
	->appendStylesheet('/css/52framework/general.css')
	->appendStylesheet('/css/main.css');
$this->jQuery()
	->setLocalPath('/js/jquery-1.6.1.min.js')
	->addJavascriptFile('/js/modernizr-1.7.min.js')
	->addJavascriptFile('/js/jquery.corner.js')
	->enable();
$this->headTitle($this->pageTitle)
	->setSeparator(' | ')
	->headTitle($this->translate('app.name'));
$this->jQuery()->addOnLoad('
	$(".pageSubHeader .navigation, .notice").corner("5px");
	$(".pageSubHeader .navigation .first").corner("5px left");
	$(".pageSubHeader .navigation .last").corner("5px right");
');
?>

<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"/>

	<?=$this->headTitle();?>
	<?=$this->headLink();?>
	<?=$this->jQuery();?>
</head>

<body>
	<div class="pageHeaderWrapper"><div class="pageHeader pageSection">
		<div class="loginBox"><?=$this->loggedInAs();?></div>
		<div class="siteName"><a href="/"><img src="/img/logo.png" alt="keboolytics" /></a></div>
	</div></div>
	<?if($this->user){?>
	<div class="pageSubHeaderWrapper"><div class="pageSubHeader pageSection">
		<?=$this->navigation()->menu()->render();?>
	</div></div>
	<?}?>
	<div class="pageTitleWrapper"><div class="pageTitle pageSection">
		<h1><?=$this->pageTitle?></h1>
	</div></div>
	<div class="pageContentWrapper"><div class="pageContent pageSection">
		<?=$this->layout()->content;?>
	</div></div>
	<div class="pageFooterWrapper"><div class="pageFooter pageSection">
		<p><?=$this->translate('layout.footer')?></p>
	</div></div>
</body>
</html>


