<?
$this->headLink()
	->appendStylesheet('/css/52framework/reset.css')
	->appendStylesheet('/css/52framework/css3.css')
	->appendStylesheet('/css/52framework/general.css')
	->appendStylesheet('/css/main.css')
	->appendStylesheet('/css/ie.css', 'all', 'ie');
$this->jQuery()
	->setLocalPath('/js/jquery-1.6.1.min.js')
	->addJavascriptFile('/js/modernizr-1.7.min.js')
	->addJavascriptFile('/js/jquery.corner.js')
	->enable();
?>

<!DOCTYPE HTML>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"/>

	<?=$this->headTitle();?>
	<?=$this->headLink();?>
	<?=$this->jQuery();?>
</head>
<?php
	$config = Zend_Registry::get('config');
?>
<body>	

	<div class="pageHeaderWrapper">
		<div class="pageHeader pageSection">
			<div class="loginBox">
				<a target="_blank" href="http://www.facebook.com/dialog/pagetab?app_id=<?=$config->facebook->appId;?>&next=<?=$config->app->url;?>" class="right">Přidat aplikaci na stránku</a><br />
			</div>
			<div class="siteName"><a href="/account"><img src="/img/logo.png" alt=""></a></div>			
		</div>
	</div>

	<div class="pageTitleWrapper"><div class="pageTitle pageSection">
		<h1>Keboola Fans Checker</h1>
	</div></div>

	<div class="pageContentWrapper"><div class="pageContent pageSection">
		<?=$this->layout()->content;?>
	</div></div>

	<div class="pageFooterWrapper"><div class="pageFooter pageSection">
		<p>© <a href="http://keboola.com">Keboola</a> | <a href="http://keboola.zendesk.com">
			Support</a></p>
	</div></div>
		
</body>
</html>


