<!DOCTYPE HTML>
<html>
	<head>
		<meta charset=utf-8>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>

		<title>Facebook GoodData Connector</title>

		<script src="/js/modernizr-1.7.min.js"></script>
		<script src="/js/jquery-1.6.1.min.js"></script>
		<script src="/js/imagePreview.js"></script>

		<link rel="stylesheet" type="text/css" href="/css/52framework/reset.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="/css/52framework/css3.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="/css/52framework/general.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="/css/52framework/forms.css" media="screen" />
    	<link rel="stylesheet" type="text/css" href="/css/main.css" media="screen" />
	</head>

	<body>
		<div class="pageHeader">
			<img src="/img/keboola.png" />
			<h1>Facebook GoodData Connector Setup</h1>
		</div>
		<div class="pageContent">
<?=$this->layout()->content;?>
		</div>
	</body>
</html>


