<?
$this->headLink()
	->appendStylesheet('/css/52framework/reset.css')
	->appendStylesheet('/css/52framework/css3.css')
	->appendStylesheet('/css/52framework/general.css')
	->appendStylesheet('/css/main.css')
	->appendStylesheet('/css/simple.css')
	->appendStylesheet('/css/ie.css', 'all', 'ie');
$this->jQuery()
	->setLocalPath('/js/jquery-1.6.1.min.js')
	->addJavascriptFile('/js/modernizr-1.7.min.js')
	->addJavascriptFile('/js/jquery.corner.js')
	->enable();
$this->headTitle($this->pageTitle)
	->setSeparator(' | ')
	->headTitle($this->translate('app.name'));
$this->jQuery()->addOnLoad('
	$(".inputText input").corner("3px");
	$(".loginErrors").corner("5px");
');

if ($this->iframe){
	$this->headLink()->appendStylesheet('/css/iframe.css');
}

if ($this->messages){
	$this->headStyle()->appendStyle('.loginErrors { display: block }');
}
?>

<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"/>

	<?=$this->headTitle();?>
	<?=$this->headLink();?>
	<?=$this->headStyle();?>
	<?=$this->headScript();?>
	<?=$this->jQuery();?>
</head>

<body>
<?if(!$this->iframe) {?>
	<div class="pageHeaderWrapper"><div class="pageHeader pageSection">
		<div class="loginBox"><?=$this->loggedInAs();?></div>
		<div class="siteName"><a href="/"><img src="/img/logo.png" alt="Keboola Analytics" /></a></div>
	</div></div>
<?}?>
	<div class="pageContentWrapper"><div class="pageContent pageSection">
		<?=$this->layout()->content;?>
	</div></div>
<?if(!$this->iframe) {?>
	<div class="pageFooter pageSection">
		<p>&copy; <a href="http://keboola.com">Keboola</a> | <a href="<?=$this->config->app->support->url?>">
			<?=$this->translate('layout.support')?></a></p>
	</div>
<?}?>
	<script type="text/javascript">
		var GoSquared={};
		GoSquared.acct = "GSN-148523-Z";
		(function(w){
			function gs(){
				w._gstc_lt=+(new Date); var d=document;
				var g = d.createElement("script"); g.type = "text/javascript"; g.async = true; g.src = "//d1l6p2sc9645hc.cloudfront.net/tracker.js";
				var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(g, s);
			}
			w.addEventListener?w.addEventListener("load",gs,false):w.attachEvent("onload",gs);
		})(window);
	</script>
	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-27344639-1']);
		_gaq.push(['_trackPageview']);
		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	</script>
</body>
</html>


